### ISSUE TITLE
Blank extension window

### ISSUE THREAD

**Issue by 3ricsonn** [Myzel394/domaincountry#89]
The extension icon still indicates the country where the server of the loaded page is located, but when clicked, it just pops a blank window, where other information should be.
![domaincountry_bug](https://user-images.githubusercontent.com/68168688/134201965-53610c4a-d05d-4593-aec1-157f9c06519d.png)

**Comment by Myzel394** [comment]
fixed in version 0.1.5.

**Comment by 3ricsonn** [comment]
👍
